#!/bin/bash -l

#$ -l h_rt=24:00:00
#$ -l mem=4G
#$ -l tmpfs=20G
#$ -pe smp 36
#$ -l matlab=1
#$ -N spm_microstates
#$ -wd /home/<UCL_id>/Scratch/SPM_MS

set -e

module load xorg-utils/X11R7.7
module load matlab/full/r2021a/9.10
module list

cd "$TMPDIR"

cat > run_pipeline.m <<'MATLAB_EOF'
addpath(genpath('/home/<UCL_id>/Scratch/SPM_MS'));

T = Bayesian_MS_Comparison_Pipeline( ...
    'out_dir', '/home/<UCL_id>/Scratch/SPM_MS/Output/cluster_run', ...
    'reps', 8, ...
    'K_true_vals', [4 5 6 7], ...
    'SNR_dbs', [-9 -3 0 1 3], ...
    'K_candidates', 2:10, ...
    'duration_s', 300, ...
    'sfreq', 250, ...
    'set_file', '/home/<UCL_id>/Scratch/SPM_MS/MetaMaps_2023_06.set', ...
    'n_workers', 36, ...
    'montages', {'full','10-20-20','10-20-12'}, ...
    'overlap_probs', [0 0.5 1.0], ...
    'validate_simulation', true, ...
    'verbose', true);

exit;
MATLAB_EOF

matlab -nosplash -nodesktop -nodisplay < run_pipeline.m